name: personality-analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - gensim
  - jupyter
  - jupyterlab
  - keras
  - matplotlib
  - pandas
  - pip
  - python=3.10.2
  - scikit-learn
  - sphinx
  - tensorflow
#  - pip:
#      - Flask-Testing
